---
- name: Check if Rust is installed
  ansible.builtin.shell: |
    command -v cargo
  register: rust_check
  failed_when: false
  changed_when: false

- name: Install Rust toolchain
  when: rust_check.rc != 0
  block:
    - name: Download Rust installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: '0755'

    - name: Install Rust
      ansible.builtin.shell: |
        /tmp/rustup.sh -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo"

    - name: Remove Rust installer
      ansible.builtin.file:
        path: /tmp/rustup.sh
        state: absent

- name: Update PATH for Rust
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    create: true
    state: present

- name: Install Rust nightly toolchain
  ansible.builtin.shell: |
    source $HOME/.cargo/env && rustup toolchain install nightly
  args:
    executable: /bin/bash
  changed_when: false

- name: Install Rust components
  ansible.builtin.shell: |
    source $HOME/.cargo/env && rustup component add rustfmt clippy
  args:
    executable: /bin/bash
  changed_when: false

- name: Install cargo-ament-build
  ansible.builtin.shell: |
    source $HOME/.cargo/env && cargo install cargo-ament-build
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.cargo/bin/cargo-ament-build"