[package]
name = "lidar_board_detector"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
arc-swap = "1.7"
board-cluster-detector = { version = "0.1.0", path = "../../rust/board-cluster-detector" }
calibration-target = { version = "0.1.0", path = "../../rust/calibration-target" }
calibration-target-detector = { version = "0.1.0", path = "../../rust/calibration-target-detector" }
env_logger = "0.11"
geometry_msgs.workspace = true
json5 = { workspace = true }
lctk_interfaces = "*"
ndarray = "0.16"
once_cell = { workspace = true }
pcd-rs = { workspace = true }
petal-decomposition = { version = "0.8", features = ["openblas-system"] }
rclrs.workspace = true
sensor_msgs.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
std_msgs.workspace = true
std_srvs = "*"
vision_msgs.workspace = true
visualization_msgs.workspace = true

[dependencies.nalgebra]
workspace = true

[[bin]]
name = "lidar_board_detector"
path = "src/main.rs"
