#!/usr/bin/env python3

import sys
import os

# Add the package path to Python path - dynamically detect Python version
import platform
python_version = f"python{platform.python_version_tuple()[0]}.{platform.python_version_tuple()[1]}"
package_path = os.path.join(os.path.dirname(__file__), '..', 'lib', python_version, 'site-packages')
if package_path not in sys.path:
    sys.path.insert(0, package_path)

from simple_extrinsic_solver_py.main import main

if __name__ == '__main__':
    main()
