//! Golden-vector fixture loader shared by parity tests.
//!
//! Fixtures live under `tests/fixtures/` and are generated by
//! `experiments/board-detection-2d/tools/export_golden.py`. See
//! `tests/fixtures/README.md` for the format and regeneration command.

use nalgebra::Point3;
use serde::Deserialize;
use std::{
    fs,
    path::{Path, PathBuf},
};

#[derive(Debug, Deserialize)]
pub struct BgParams {
    pub voxel: f64,
    pub dilation_radius: i64,
    pub min_sources: usize,
}

#[derive(Debug, Deserialize)]
pub struct Golden {
    pub generator: String,
    #[serde(default)]
    pub dataset: Option<u32>,
    pub voxel: f64,
    pub up_axis: [f64; 3],
    pub cluster_min_points: usize,
    #[serde(default)]
    pub background_keys_file: Option<String>,
    #[serde(default)]
    pub background_params: Option<BgParams>,
    #[serde(default)]
    pub foreground_xyz: Vec<[f64; 3]>,
    pub n_candidates: usize,
    #[serde(default)]
    pub selected_centroid: Option<[f64; 3]>,
    #[serde(default)]
    pub selected_corners_3d: Option<Vec<[f64; 3]>>,
    pub detected: bool,
    #[serde(default)]
    pub true_board: bool,
}

/// Load a sibling `<name>.bgkeys.i64` (raw LE i64) into a sorted Vec<i64>.
pub fn load_i64(path: &Path) -> Vec<i64> {
    fs::read(path)
        .unwrap()
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

pub struct Fixture {
    pub name: String,
    pub input: Vec<Point3<f64>>,
    pub golden: Golden,
}

pub fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

pub fn load_f32(path: &Path) -> Vec<Point3<f64>> {
    let bytes = fs::read(path).unwrap();
    bytes
        .chunks_exact(12)
        .map(|c| {
            let f = |i: usize| f32::from_le_bytes(c[i * 4..i * 4 + 4].try_into().unwrap()) as f64;
            Point3::new(f(0), f(1), f(2))
        })
        .collect()
}

pub fn load_all() -> Vec<Fixture> {
    let dir = fixtures_dir();
    let mut out = vec![];
    for e in fs::read_dir(&dir).unwrap() {
        let p = e.unwrap().path();
        if p.extension().and_then(|x| x.to_str()) != Some("json") {
            continue;
        }
        let name = p
            .file_stem()
            .unwrap()
            .to_str()
            .unwrap()
            .trim_end_matches(".golden")
            .to_string();
        let golden: Golden = serde_json::from_str(&fs::read_to_string(&p).unwrap()).unwrap();
        let input = load_f32(&dir.join(format!("{name}.input.f32")));
        out.push(Fixture {
            name,
            input,
            golden,
        });
    }
    out
}
