---
- name: Check if rosdep is initialized
  ansible.builtin.stat:
    path: /etc/ros/rosdep/sources.list.d/20-default.list
  register: rosdep_initialized

- name: Initialize rosdep (system-wide)
  become: true
  ansible.builtin.shell: |
    rosdep init
  when: not rosdep_initialized.stat.exists
  changed_when: true

- name: Check if rosdep database is updated
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ros/rosdep/sources.cache"
  register: rosdep_cache

- name: Update rosdep database (user)
  ansible.builtin.shell: |
    rosdep update
  when: not rosdep_cache.stat.exists or (ansible_date_time.epoch|int - rosdep_cache.stat.mtime|int > 86400)
  changed_when: true
  environment:
    ROSDEP_UPDATE_QUIET: "true"

- name: Check if LCTK source directory exists
  ansible.builtin.stat:
    path: "{{ lctk_root }}/src"
  register: src_dir

- name: Install ROS dependencies from package.xml files
  ansible.builtin.shell: |
    source /opt/ros/humble/setup.bash && \
    rosdep install --from-paths src --ignore-src -y --rosdistro humble
  args:
    chdir: "{{ lctk_root }}"
    executable: /bin/bash
  when: src_dir.stat.exists
  changed_when: false
  register: rosdep_install
  failed_when:
    - rosdep_install.rc != 0
    - '"All required rosdeps installed successfully" not in rosdep_install.stderr'
