[workspace]
resolver = "2"
members = [
    "rust-bin/find-aruco-marker",
    "rust-bin/find-hollow-board",
    "rust-bin/pcd-tool",
    "rust-bin/project-to-image",
    "rust-bin/solve-extrinsic-params",
    "rust-bin/multi_wayside",
    "rust-lib/aruco-config",
    "rust-lib/aruco-detector",
    "rust-lib/hollow-board-config",
    "rust-lib/hollow-board-detector",
    "rust-lib/pcd-format",
    "rust-lib/plane-estimator",
    "rust-lib/pnp-solver",
    "rust-lib/serde-types",
]
