[package]
name = "plane-estimator"
version = "0.1.1"
edition = "2021"

[dependencies]
nalgebra = { workspace = true }
sample-consensus = "1.0.2"
simba = "0.8.1"

[dev-dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
kiss3d = { workspace = true }
pcd-rs = { workspace = true }
