[package]
name = "plane-estimator"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.30.1"
sample-consensus = "1.0.2"
simba = "0.7.0"

[dev-dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.0", features = ["derive"] }
itertools = "0.11.0"
kiss3d = "0.35.0"
pcd-rs = "0.10.0"
