[package]
name = "pnp-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "0.69.0", default-features = false, features = ["calib3d"] }
common-types = { path = "../common-types", features = ["with-opencv", "with-nalgebra"] }
cv-convert = { version = "0.21.0", default-features = false, features = ["opencv_0-69", "nalgebra_0-30"] }
serde = { version = "1.0.145", features = ["derive"] }
nalgebra = "0.30.1"
log = "0.4.17"
strum = { version = "0.24.1", features = ["derive"] }
