[package]
name = "pnp-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.84.5"
serde-types = { path = "../serde-types", features = ["with-opencv", "with-nalgebra"] }
cv-convert = { version = "0.24.1", default-features = false, features = ["opencv_0-84", "nalgebra_0-30"] }
serde = { version = "1.0.188", features = ["derive"] }
nalgebra = "0.30.1"
log = "0.4.20"
strum = { version = "0.25.0", features = ["derive"] }
