[package]
name = "aruco-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-loader = { version = "0.1.4", features = ["json5"] }
measurements = "0.11.0"
noisy_float = { version = "0.2.0", features = ["serde"] }
opencv = { version = "0.69.0", optional = true, default-features = false, features = ["aruco"] }
serde = { version = "1.0.140", features = ["derive"] }
common-types = { version = "0.1.0", path = "../common-types", features = ["with-measurements"] }

[features]
with-opencv = ["opencv"]
