[package]
name = "hollow-board-config"
version = "0.1.1"
edition = "2021"

[dependencies]
nalgebra = { workspace = true }
approx = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
aruco-config = { version = "0.1.0", path = "../aruco-config" }
measurements = { workspace = true, features = ["serde"] }
rayon = { version = "1.10", optional = true }

newslab-serde-measurements = { workspace = true }
newslab-serde-nalgebra = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
noisy_float = { workspace = true }

[features]
parallel = ["rayon"]
