[package]
name = "kiss3d-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
kiss3d = "0.35.0"
nalgebra = "0.30.1"
simba = "0.7.0"
