#!/usr/bin/env python3
"""Generate ``marker_corners_world.golden.json``.

This is the *independent* side of a cross-language contract. It derives every world
coordinate in the fixture from two things only:

  1. the printed ArUco pattern's dimensions (``config/aruco/aruco_pattern.json5``), and
  2. a stated physical mounting of the plate.

It deliberately does **not** call, import, or shell out to the Rust implementation. Its
whole value is that it can disagree with it.

The fixture pins *physical* positions, so it must survive the corner-aligned board-frame
change (docs/superpowers/specs/2026-08-13-corner-aligned-board-frame.md) byte-identical.
Regenerate it only when the printed board itself changes — never to make a failing test
pass.

Usage:
    python3 generate_marker_corners_world.py > marker_corners_world.golden.json
"""

import json
import math
import sys

# ---------------------------------------------------------------------------
# The printed board, from config/aruco/aruco_pattern.json5 and the board-detector
# presets (board_width).
# ---------------------------------------------------------------------------
BOARD_WIDTH_M = 1.0  # plate edge length
MARKER_PAPER_SIZE_M = 0.5  # aruco_pattern.board_size
BOARD_BORDER_SIZE_M = 0.01  # aruco_pattern.board_border_size
NUM_SQUARES_PER_SIDE = 2
MARKER_SQUARE_SIZE_RATIO = 0.8
# x-major order by (x, y): index 0 -> (col 0, row 0), 1 -> (col 1, row 0), ...
MARKER_IDS = [696, 64, 306, 195]

# ---------------------------------------------------------------------------
# The stated physical mounting.
#
# A vertical plate 3 m in front of the sensor, hung as a diamond: the plate's
# diagonals run straight up and horizontally, so the up-most point of the board is a
# corner. The normal points back at the sensor (-X).
# ---------------------------------------------------------------------------
PLATE_CENTER = (3.0, 0.5, 1.2)
NORMAL = (-1.0, 0.0, 0.0)  # toward the sensor at the origin
UP_DIAGONAL = (0.0, 0.0, 1.0)  # centre -> up-most corner


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def add(p, v):
    return (p[0] + v[0], p[1] + v[1], p[2] + v[2])


def scale(v, s):
    return (v[0] * s, v[1] * s, v[2] * s)


def normalize(v):
    n = math.sqrt(sum(c * c for c in v))
    return scale(v, 1.0 / n)


def main():
    normal = normalize(NORMAL)
    up = normalize(UP_DIAGONAL)
    # Toward the left corner. Same handedness rule the Rust test uses:
    # (left, up, normal) is right-handed.
    left_dir = normalize(cross(up, normal))

    half_diagonal = BOARD_WIDTH_M / math.sqrt(2.0)
    top = add(PLATE_CENTER, scale(up, half_diagonal))
    bottom = add(PLATE_CENTER, scale(up, -half_diagonal))
    left = add(PLATE_CENTER, scale(left_dir, half_diagonal))
    right = add(PLATE_CENTER, scale(left_dir, -half_diagonal))

    # The marker paper is glued flat to the plate, its edges parallel to the plate's
    # edges, with its origin corner on the plate's bottom corner. Paper axes:
    #   +u runs bottom corner -> left corner, +v runs bottom corner -> right corner.
    # This is a physical statement and is what the frame change must preserve.
    u_axis = normalize(tuple(l - b for l, b in zip(left, bottom)))
    v_axis = normalize(tuple(r - b for r, b in zip(right, bottom)))

    def paper_to_world(pu, pv):
        return add(add(bottom, scale(u_axis, pu)), scale(v_axis, pv))

    square_size = (
        MARKER_PAPER_SIZE_M - 2.0 * BOARD_BORDER_SIZE_M
    ) / NUM_SQUARES_PER_SIDE
    marker_size = square_size * MARKER_SQUARE_SIZE_RATIO
    marker_border = (square_size - marker_size) / 2.0
    origin = BOARD_BORDER_SIZE_M + marker_border

    markers = {}
    for index, marker_id in enumerate(MARKER_IDS):
        col = index % NUM_SQUARES_PER_SIDE
        row = index // NUM_SQUARES_PER_SIDE
        base_u = origin + col * square_size
        base_v = origin + row * square_size
        # Corner order [right, top, left, bottom], matching the detector's contract
        # with the ArUco corner ordering downstream.
        markers[str(marker_id)] = [
            list(paper_to_world(base_u, base_v + marker_size)),  # right
            list(paper_to_world(base_u + marker_size, base_v + marker_size)),  # top
            list(paper_to_world(base_u + marker_size, base_v)),  # left
            list(paper_to_world(base_u, base_v)),  # bottom
        ]

    fixture = {
        "_comment": (
            "World-coordinate golden for the ArUco marker layout. Physical positions "
            "only: must pass unchanged across the corner-aligned board-frame change. "
            "Generated by generate_marker_corners_world.py; do not re-baseline."
        ),
        "board_width_m": BOARD_WIDTH_M,
        "marker_paper_size_m": MARKER_PAPER_SIZE_M,
        "pattern": {
            "marker_ids": MARKER_IDS,
            "board_border_size_m": BOARD_BORDER_SIZE_M,
            "num_squares_per_side": NUM_SQUARES_PER_SIDE,
            "marker_square_size_ratio": MARKER_SQUARE_SIZE_RATIO,
        },
        "mounting": {
            "plate_center": list(PLATE_CENTER),
            "normal": list(NORMAL),
            "up_diagonal": list(UP_DIAGONAL),
        },
        "plate_corners": {
            "top": list(top),
            "bottom": list(bottom),
            "left": list(left),
            "right": list(right),
            "center": list(PLATE_CENTER),
        },
        "marker_corner_order": ["right", "top", "left", "bottom"],
        "markers": markers,
    }

    json.dump(fixture, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
