//! Golden-vector fixture loader shared by parity tests.
#![allow(deprecated)] // Shared legacy fixture helpers.
//!
//! Fixtures live under `tests/fixtures/` and are generated by
//! `experiments/board-detection-2d/tools/export_golden.py`. See
//! `tests/fixtures/README.md` for the format and regeneration command.
#![allow(dead_code)] // shared fixture-loader scaffolding; fields/helpers consumed by later tasks

use board_cluster_detector::{
    background::BackgroundModel,
    candidates::{generate_background_diff, generate_plane_strip},
    config::{
        production_config, production_tuning, ForegroundMethod, TargetDetectionParams, TargetSide,
    },
    detector::detect,
    geometry,
};
use nalgebra::Point3;
use serde::Deserialize;
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

#[derive(Debug, Deserialize)]
pub struct BgParams {
    pub voxel: f64,
    pub dilation_radius: i64,
    pub min_sources: usize,
}

#[derive(Debug, Deserialize)]
pub struct Golden {
    pub generator: String,
    #[serde(default)]
    pub dataset: Option<u32>,
    pub voxel: f64,
    pub up_axis: [f64; 3],
    pub cluster_min_points: usize,
    #[serde(default)]
    pub background_keys_file: Option<String>,
    #[serde(default)]
    pub background_params: Option<BgParams>,
    #[serde(default)]
    pub foreground_xyz: Vec<[f64; 3]>,
    pub n_candidates: usize,
    #[serde(default)]
    pub selected_centroid: Option<[f64; 3]>,
    #[serde(default)]
    pub selected_corners_3d: Option<Vec<[f64; 3]>>,
    pub detected: bool,
    #[serde(default)]
    pub true_board: bool,
}

/// Load a sibling `<name>.bgkeys.i64` (raw LE i64) into a sorted Vec<i64>.
pub fn load_i64(path: &Path) -> Vec<i64> {
    fs::read(path)
        .unwrap()
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

pub struct Fixture {
    pub name: String,
    pub input: Vec<Point3<f64>>,
    pub golden: Golden,
}

pub fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

pub fn load_f32(path: &Path) -> Vec<Point3<f64>> {
    let bytes = fs::read(path).unwrap();
    bytes
        .chunks_exact(12)
        .map(|c| {
            let f = |i: usize| f32::from_le_bytes(c[i * 4..i * 4 + 4].try_into().unwrap()) as f64;
            Point3::new(f(0), f(1), f(2))
        })
        .collect()
}

impl Fixture {
    /// True for fixtures generated by the `background_subtraction` (Method
    /// E) candidate generator -- the only ones carrying `bgkeys.i64` +
    /// `background_params`.
    pub fn generator_is_bg(&self) -> bool {
        self.golden.generator == "background_subtraction"
    }
}

/// Fraction of `expected` golden points that have a matching `actual` point
/// within `tol` (nearest-neighbour, brute force -- fixture sizes are small).
///
/// Directional (recall against the golden set) rather than symmetric: the
/// known voxel-grid-anchoring mismatch between Rust's origin-anchored
/// `voxel_downsample` and open3d's bbox-anchored one can produce a handful of
/// extra/missing points near cell boundaries on either side, so a loose
/// bidirectional check would mask real regressions. Matching against golden
/// membership is the more conservative direction.
pub fn foreground_match(actual: &[Point3<f64>], expected: &[[f64; 3]], tol: f64) -> f64 {
    if expected.is_empty() {
        return 1.0;
    }
    let hits = expected
        .iter()
        .filter(|e| {
            actual.iter().any(|a| {
                let (dx, dy, dz) = (a.x - e[0], a.y - e[1], a.z - e[2]);
                (dx * dx + dy * dy + dz * dz).sqrt() <= tol
            })
        })
        .count();
    hits as f64 / expected.len() as f64
}

/// Rebuild the exported Python `BackgroundModel` for `f` via `from_keys`,
/// recompute `foreground_points` on the fixture's own downsampled input, and
/// assert >= 95% membership match against `f.golden.foreground_xyz`.
///
/// # Panics
/// If `f` isn't a `background_subtraction` fixture (missing
/// `background_keys_file` / `background_params`), or if the match falls
/// below 95%.
pub fn assert_foreground_parity(f: &Fixture) {
    let keys_file = f
        .golden
        .background_keys_file
        .as_ref()
        .unwrap_or_else(|| panic!("{}: missing background_keys_file", f.name));
    let params = f
        .golden
        .background_params
        .as_ref()
        .unwrap_or_else(|| panic!("{}: missing background_params", f.name));
    let keys = load_i64(&fixtures_dir().join(keys_file));
    let bg = BackgroundModel::from_keys(
        keys,
        params.voxel,
        params.dilation_radius,
        params.min_sources,
    );

    let finite = geometry::finite_only(&f.input);
    let dn = geometry::voxel_downsample(&finite, f.golden.voxel);
    let fg = bg.foreground_points(&dn);

    let match_frac = foreground_match(&fg, &f.golden.foreground_xyz, f.golden.voxel);
    assert!(
        match_frac >= 0.95,
        "{}: foreground parity {:.1}% below 95% threshold (rust={} pts, golden={} pts)",
        f.name,
        match_frac * 100.0,
        fg.len(),
        f.golden.foreground_xyz.len()
    );
}

/// Mean of a candidate's member points (NOT the same quantity as
/// `golden.selected_centroid`, which is the fitted board's 4-corner mean --
/// see `assert_candidate_parity`).
fn candidate_centroid(points: &[Point3<f64>]) -> [f64; 3] {
    let n = points.len() as f64;
    let sum = points.iter().fold([0.0; 3], |mut acc, p| {
        acc[0] += p.x;
        acc[1] += p.y;
        acc[2] += p.z;
        acc
    });
    [sum[0] / n, sum[1] / n, sum[2] / n]
}

fn dist3(a: &[f64; 3], b: &[f64; 3]) -> f64 {
    let (dx, dy, dz) = (a[0] - b[0], a[1] - b[1], a[2] - b[2]);
    (dx * dx + dy * dy + dz * dz).sqrt()
}

/// Fixtures whose per-frame detect/no-detect decision is KNOWN to diverge from
/// the Python golden. This is NOT bit-exact parity — it cannot be: open3d's
/// `segment_plane` RANSAC and its DBSCAN use their own RNG stream, so Method B
/// (`plane_strip`) candidate boundaries and Method E's clustering differ frame
/// to frame from this port's seeded-deterministic RANSAC/DBSCAN. The controller
/// (user-approved) accepts this: the hard gate is
/// `recall_precision_parity_per_dataset` (aggregate recall/precision within ±1
/// per dataset/generator), which passes. Each entry below is a documented,
/// stable divergence; `per_frame_detection_decision_matches_python` asserts the
/// ACTUAL mismatch set is a SUBSET of this list, so any NEW divergence fails as
/// a regression, and `candidate_parity_against_python` skips these frames (a
/// Method-B divergence leaves no board-near candidate — its centroid is far from
/// golden by construction). Because our RANSAC/DBSCAN are seeded (seed 0), this
/// set is reproducible run to run. Full evidence:
/// `.superpowers/sdd/2026-07-29-board-cluster-detector-rust-library/task-9-report.md`.
pub const KNOWN_PER_FRAME_MISMATCHES: &[&str] = &[
    // Method E — clean false positive: Rust's clustering (RNG-dependent) found a
    // clean board-shaped square (residual 0.25, stance 0.999, iso 0) that
    // Python's pipeline did not accept on this frame. (golden.detected=false, so
    // candidate_parity already skips it.)
    "ds2_f0008_ba",
    // Method B — clean false positive: a candidate passes all gates comfortably
    // (residual 0.30, stance 0.9995, iso 0); candidate-generation split.
    // (golden.detected=false.)
    "ds1_f0000_pl",
    // Method B — foreground-stage divergence: board cluster sits against a wall
    // (best stance 0.736, iso 79.5), no clean isolated square among candidates.
    // Method E detects this board correctly.
    "ds1_f0002_pl",
    // Method B — foreground-stage divergence: board fragments, no candidate
    // forms a clean square (best square-residual 0.775). Method E detects it.
    "ds1_f0068_pl",
    // Method B — BORDERLINE gate tie: best stance 0.8893 vs 0.9 floor (off by
    // 0.011); a float tie, not fixable without overfitting the threshold.
    "ds2_f0000_pl",
    // Method B — clean false positive: second candidate passes cleanly
    // (residual 0.375, stance 0.999, iso 0); candidate-generation split.
    // (golden.detected=false.)
    "ds2_f0034_pl",
    // Method B — foreground-stage divergence: board cluster not forming a clean
    // square (best square-residual 0.5447 > 0.45).
    "ds2_f0068_pl",
    // Method B — foreground-stage divergence: board-ish clusters coplanar with a
    // wall (iso 81.5 / 15.0); Python isolated it better. Method E detects it.
    // (candidate exists at 0.105 m, but the frame is rejected downstream at the
    // isolation gate — still listed as the accepted per-frame divergence.)
    "ds3_f0000_pl",
    // Method B — BORDERLINE gate tie: best square-residual 0.4618 vs 0.45 max
    // (off by 0.012); a float tie, not fixable without overfitting.
    "ds5_f0068_pl",
];

/// Centroid-match tolerance (see `assert_candidate_parity`'s doc comment for
/// why this isn't 0.02 m).
///
/// Measured with the plain seeded RANSAC (`candidates::ransac_plane_inliers`,
/// matching open3d `segment_plane`): across the `detected=true` fixtures NOT in
/// `KNOWN_PER_FRAME_MISMATCHES` (the frames this port detects in agreement with
/// Python), the nearest candidate centroid is 0.041-0.136 m from
/// `golden.selected_centroid`; 0.14 m gives ~4 mm of margin above the observed
/// max (0.1358 m, ds1_f0034_pl) without papering over a real mismatch -- a
/// genuine miss lands far outside this band (the documented Method-B divergence
/// frames measure 0.15-0.37 m and are skipped, not tolerated).
pub const CANDIDATE_CENTROID_TOL: f64 = 0.14;

/// Run the fixture's matching candidate generator on `downsample(finite_only(input))`
/// and check it against the golden vector produced by
/// `experiments/board-detection-2d/tools/export_golden.py`.
///
/// Two assertions, chosen to be robust to the exact clustering split (which
/// candidate boundaries fall on is not asserted point-for-point -- see the
/// task-5 brief and Task 9's note on RANSAC-selection-only parity):
/// - when `golden.detected`, at least one produced candidate exists and its
///   centroid is within `CANDIDATE_CENTROID_TOL` of `golden.selected_centroid`.
///   `selected_centroid` is `det.center`: the mean of the 4 ICP-square-fitted
///   corners (`pose.py:board_pose`), a downstream (Task 9+) refinement --
///   NOT the mean of the candidate's raw member points computed here. The
///   two are close (both describe "the board") but not identical, so the
///   natural gap is larger than a golden-vector point-for-point tolerance
///   would be.
/// - a sane floor: `detected` implies `n_candidates >= 1` from this port too.
pub fn assert_candidate_parity(f: &Fixture) {
    // Documented Method-B/E per-frame divergences (RNG-driven, controller-
    // accepted) legitimately produce no board-near candidate -- skip them here;
    // the aggregate gate is `recall_precision_parity_per_dataset`.
    if KNOWN_PER_FRAME_MISMATCHES.contains(&f.name.as_str()) {
        return;
    }
    let finite = geometry::finite_only(&f.input);
    let dn = geometry::voxel_downsample(&finite, f.golden.voxel);
    let tuning = production_tuning(f.golden.up_axis, f.golden.cluster_min_points);
    let target_params = TargetDetectionParams::new(TargetSide::metres(1.0).unwrap(), &tuning);

    let cands = if f.generator_is_bg() {
        let keys_file = f
            .golden
            .background_keys_file
            .as_ref()
            .unwrap_or_else(|| panic!("{}: missing background_keys_file", f.name));
        let params = f
            .golden
            .background_params
            .as_ref()
            .unwrap_or_else(|| panic!("{}: missing background_params", f.name));
        let keys = load_i64(&fixtures_dir().join(keys_file));
        let bg = BackgroundModel::from_keys(
            keys,
            params.voxel,
            params.dilation_radius,
            params.min_sources,
        );
        generate_background_diff(&dn, &target_params, &bg)
    } else {
        generate_plane_strip(&dn, &target_params)
    };

    if !f.golden.detected {
        return;
    }
    assert!(
        !cands.is_empty(),
        "{}: golden detected a board but this port produced 0 candidates",
        f.name
    );
    let expected = f
        .golden
        .selected_centroid
        .unwrap_or_else(|| panic!("{}: detected=true but no selected_centroid", f.name));
    let best = cands
        .iter()
        .map(|c| dist3(&candidate_centroid(&c.points), &expected))
        .fold(f64::INFINITY, f64::min);
    assert!(
        best <= CANDIDATE_CENTROID_TOL,
        "{}: nearest candidate centroid is {best:.4} m from golden.selected_centroid \
         (tol={CANDIDATE_CENTROID_TOL})",
        f.name
    );
}

/// Map a fixture to its detector inputs: the foreground method and (for
/// `background_subtraction` fixtures) the exported background model rebuilt
/// from its `.bgkeys.i64` file.
pub fn method_and_background(f: &Fixture) -> (ForegroundMethod, Option<BackgroundModel>) {
    if f.generator_is_bg() {
        let keys_file = f
            .golden
            .background_keys_file
            .as_ref()
            .unwrap_or_else(|| panic!("{}: missing background_keys_file", f.name));
        let params = f
            .golden
            .background_params
            .as_ref()
            .unwrap_or_else(|| panic!("{}: missing background_params", f.name));
        let keys = load_i64(&fixtures_dir().join(keys_file));
        let bg = BackgroundModel::from_keys(
            keys,
            params.voxel,
            params.dilation_radius,
            params.min_sources,
        );
        (ForegroundMethod::BackgroundSubtraction, Some(bg))
    } else {
        (ForegroundMethod::PlaneStrip, None)
    }
}

/// Reconstruct `board_pose`'s `corners_3d` via a full `detect()` run on the
/// fixture's raw input and check it against `golden.selected_corners_3d`.
///
/// Corners may come back in a rotated/cyclic order, so this is a set match:
/// every golden corner must have a Rust corner within `CORNER_MATCH_TOL`.
///
/// 3 cm was arbitrary; a uniform 5.5 cm is still tight on a 1 m board (5.5% of
/// the side) and absorbs float-noise corner matches from non-bit-exact
/// RANSAC/DBSCAN without a per-frame skip. Measured over the correctly-detected
/// fixtures (Python-detected AND agreed by this port): Method E maxes at 0.032 m,
/// Method B at 0.0510 m (ds4_f0003_pl — a single corner; that frame's board
/// CENTER still matches within 2 cm, see detect_parity's centroid assertion).
/// 0.055 m leaves ~4 mm of margin above that max; a genuinely-wrong board would
/// miss by >> 0.1 m. (The controller's initial 0.04 was set before ds4_f0003_pl's
/// 0.051 m was visible — iteration order had masked it behind ds5_f0022_pl's
/// 0.031 m; see task-9 report "Adjudication applied".)
pub const CORNER_MATCH_TOL: f64 = 0.055;

pub fn assert_pose_corners_parity(f: &Fixture) {
    let board = production_config(1.0, f.golden.up_axis, f.golden.cluster_min_points);
    let (method, bg) = method_and_background(f);
    let out = detect(&f.input, &board, method, f.golden.voxel, bg.as_ref());

    let det = out.detection.unwrap_or_else(|| {
        panic!(
            "{}: detect() found no board on a detected=true fixture",
            f.name
        )
    });
    let golden = f
        .golden
        .selected_corners_3d
        .as_ref()
        .unwrap_or_else(|| panic!("{}: detected=true but no selected_corners_3d", f.name));

    for g in golden {
        let best = det
            .corners_3d
            .iter()
            .map(|c| {
                let (dx, dy, dz) = (c.x - g[0], c.y - g[1], c.z - g[2]);
                (dx * dx + dy * dy + dz * dz).sqrt()
            })
            .fold(f64::INFINITY, f64::min);
        assert!(
            best <= CORNER_MATCH_TOL,
            "{}: golden corner {g:?} has no Rust corner within {CORNER_MATCH_TOL} m (nearest {best:.4} m)",
            f.name
        );
    }
}

/// NOTE: this is a DETECTION-PARITY subset guard over the ~4 curated fixtures
/// per (dataset, generator) — it compares Rust-detected vs Python-detected
/// counts within ±1. It is NOT the 88.4%/100% recall/precision-vs-ground-truth
/// headline metric (that lives in the experiment + task-9 report). The golden
/// `true_board` and `n_candidates` fields are intentionally not asserted here.
///
/// Aggregate detected-count per `(dataset, generator)` for both the golden
/// truth and the Rust `run` closure, and assert they agree within the
/// ±1-frame tolerance (Global Constraints).
pub fn assert_recall_precision_parity(fixtures: &[Fixture], mut run: impl FnMut(&Fixture) -> bool) {
    let mut py: BTreeMap<(u32, String), i64> = BTreeMap::new();
    let mut rs: BTreeMap<(u32, String), i64> = BTreeMap::new();
    for f in fixtures {
        let ds = f
            .golden
            .dataset
            .unwrap_or_else(|| panic!("{}: missing dataset id", f.name));
        let key = (ds, f.golden.generator.clone());
        py.entry(key.clone()).or_default();
        rs.entry(key.clone()).or_default();
        if f.golden.detected {
            *py.get_mut(&key).unwrap() += 1;
        }
        if run(f) {
            *rs.get_mut(&key).unwrap() += 1;
        }
    }

    let mut mism = vec![];
    for (key, &p) in &py {
        let r = rs[key];
        if (p - r).abs() > 1 {
            mism.push(format!("{key:?}: python={p} rust={r}"));
        }
    }
    assert!(
        mism.is_empty(),
        "per-(dataset,generator) detected-count mismatch > 1 frame: {mism:?}"
    );
}

pub fn load_all() -> Vec<Fixture> {
    let dir = fixtures_dir();
    let mut out = vec![];
    for e in fs::read_dir(&dir).unwrap() {
        let p = e.unwrap().path();
        if p.extension().and_then(|x| x.to_str()) != Some("json") {
            continue;
        }
        let name = p
            .file_stem()
            .unwrap()
            .to_str()
            .unwrap()
            .trim_end_matches(".golden")
            .to_string();
        let golden: Golden = serde_json::from_str(&fs::read_to_string(&p).unwrap()).unwrap();
        let input = load_f32(&dir.join(format!("{name}.input.f32")));
        out.push(Fixture {
            name,
            input,
            golden,
        });
    }
    out
}
