[package]
name = "calibration_board_locator_node"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
aruco-config = { version = "0.1.0", path = "../../rust/aruco-config" }
geometry_msgs.workspace = true
hollow-board-config = { version = "0.1.0", path = "../../rust/hollow-board-config", features = ["kiss3d"] }
hollow-board-detector = { version = "0.1.0", path = "../../rust/hollow-board-detector" }
json5 = { workspace = true }
ndarray = "0.16"
once_cell = { workspace = true }
pcd-rs = { workspace = true }
petal-decomposition = { version = "0.8", features = ["openblas-system"] }
plane-estimator = { version = "0.1.0", path = "../../rust/plane-estimator" }
rclrs.workspace = true
sensor_msgs.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
std_msgs.workspace = true
vision_msgs.workspace = true
visualization_msgs.workspace = true

[dependencies.nalgebra]
workspace = true

[[bin]]
name = "calibration_board_locator_node"
path = "src/main.rs"
