#!/usr/bin/env bash
# Synthesise the workspace-root .cargo/config.toml from colcon-cargo-ros2's
# per-package output (M-18).
#
# colcon-cargo-ros2 writes its [patch.crates-io] block into PER-PACKAGE
# .cargo/config.toml files (ros/<pkg>/.cargo/config.toml) with paths relative to
# that package, e.g. "../../build/sensor_msgs/rosidl_cargo/sensor_msgs". Cargo
# discovers config from the CWD upward, so at the workspace root no patches are
# in scope: cargo re-resolves the wildcard ROS message crates against crates.io
# and dies on the yanked sensor_msgs 4.2.3. That makes `cargo nextest run` at the
# root impossible and leaves the L-16 bindgen.lock guard reading a file that does
# not exist.
#
# The patch block is the UNION of every per-package block, not a copy of one of
# them. Each package only gets patches for the interfaces it declares, so no
# single block is a superset: aruco_generator_node has no lctk_interfaces,
# aruco_locator_node has no std_srvs/visualization_msgs, and lidar_board_detector
# has neither lifecycle_msgs nor rcl_interfaces. Copying just one of them left
# the root missing patches, which broke root-level cargo AND every package build
# that resolves the shared root workspace. That is not hypothetical: ros/*/ and
# rust/* are members of one cargo workspace, so building aruco_generator_node
# resolves aruco_locator_node's lctk_interfaces dependency too, and on a fresh
# tree it failed with "no matching package named `lctk_interfaces` found".
#
# The [build] and [env] sections stay a copy of one deterministic source: their
# values (target-dir, rustflags, AMENT_PREFIX_PATH) are per-package and absolute,
# and merging them across packages has no meaning.
#
# It is run by `just build` (after colcon, so the per-package configs are fresh)
# and by `just test`. The output is ALWAYS regenerated, never hand-maintained:
# CLAUDE.md Known Issue 1 documents that a *stale* root config makes builds fail
# with "Unable to update .../install/.../rust". /.cargo/ stays gitignored.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$repo_root"

out=.cargo/config.toml

# Pick sources deterministically so the generated file is stable across runs
# (an unstable file would churn cargo fingerprints on every build).
mapfile -t sources < <(find ros -mindepth 3 -maxdepth 3 \
    -path 'ros/*/.cargo/config.toml' -type f | sort)

if [[ ${#sources[@]} -eq 0 ]]; then
    cat >&2 <<'EOF'
error: no per-package .cargo/config.toml found under ros/*/.cargo/

  These are generated by colcon-cargo-ros2 and carry the [patch.crates-io]
  block that redirects the wildcard ROS message crates at build/ instead of
  crates.io. Without one there is nothing to synthesise a root config from,
  and cargo at the repo root will fail on the yanked sensor_msgs 4.2.3.

  Fix with:  just build
EOF
    exit 1
fi

# The [build]/[env] donor. Sorted-first keeps it stable across runs.
src=${sources[0]}

# Every patch path in a per-package config must be "../../<something>", i.e.
# relative to ros/<pkg>/. If colcon-cargo-ros2 ever changes that layout the
# naive rewrite below would produce a silently wrong root config, so refuse
# rather than guess.
for f in "${sources[@]}"; do
    if bad=$(grep -oP 'path = "\K[^"]+' "$f" | grep -v '^\.\./\.\./' || true); [[ -n "$bad" ]]; then
        echo "error: unexpected patch path shape in $f:" >&2
        printf '       %s\n' $bad >&2
        echo "       expected every path to start with ../../ (relative to ros/<pkg>/)." >&2
        echo "       colcon-cargo-ros2's output layout changed; update $0." >&2
        exit 1
    fi
done

# Union the patch entries, keyed by crate name. Two packages naming the same
# crate must agree on its path; disagreement means the generated blocks are
# describing different build trees, which we must not silently pick a winner for.
declare -A patch_line=()
declare -A patch_src=()
for f in "${sources[@]}"; do
    while IFS= read -r line; do
        name=${line%% = *}
        rewritten=${line//path = \"..\/..\//path = \"}
        if [[ -n ${patch_line[$name]:-} && ${patch_line[$name]} != "$rewritten" ]]; then
            echo "error: conflicting patch for '$name':" >&2
            echo "       ${patch_src[$name]}: ${patch_line[$name]}" >&2
            echo "       $f: $rewritten" >&2
            echo "       the per-package configs disagree; re-run 'just build' on a clean tree." >&2
            exit 1
        fi
        patch_line[$name]=$rewritten
        patch_src[$name]=$f
    done < <(grep -P '^[A-Za-z_][A-Za-z0-9_-]* = \{ path = "' "$f" || true)
done

if [[ ${#patch_line[@]} -eq 0 ]]; then
    echo "error: no [patch.crates-io] entries found in any of ros/*/.cargo/config.toml" >&2
    echo "       colcon-cargo-ros2 generated no patches; re-run 'just build'." >&2
    exit 1
fi

mkdir -p .cargo
tmp=$(mktemp "${out}.XXXXXX")
trap 'rm -f "$tmp"' EXIT

{
    echo "# GENERATED by setup/scripts/sync-root-cargo-config.sh - DO NOT EDIT."
    echo "# [patch.crates-io] is the union of every ros/*/.cargo/config.toml block,"
    echo "# with paths rewritten root-relative (M-18). [build]/[env] come from $src."
    echo "# Regenerated by every \`just build\` / \`just test\`; a stale copy breaks"
    echo "# the build (CLAUDE.md Known Issue 1). Delete it freely - it is gitignored."
    echo
    echo "[patch.crates-io]"
    for name in $(printf '%s\n' "${!patch_line[@]}" | sort); do
        echo "${patch_line[$name]}"
    done
    echo
    # target-dir, rustflags and AMENT_PREFIX_PATH are absolute already.
    sed -n '/^\[build\]/,$p' "$src"
} >"$tmp"

chmod 644 "$tmp"   # mktemp gives 0600; this file is plain generated config
mv "$tmp" "$out"
trap - EXIT

echo "root .cargo/config.toml synthesised: ${#patch_line[@]} patches from ${#sources[@]} package configs, [build]/[env] from $src"
