#!/usr/bin/env bash
# Synthesise the workspace-root .cargo/config.toml from colcon-cargo-ros2's
# per-package output (M-18).
#
# colcon-cargo-ros2 writes its [patch.crates-io] block into PER-PACKAGE
# .cargo/config.toml files (ros/<pkg>/.cargo/config.toml) with paths relative to
# that package, e.g. "../../build/sensor_msgs/rosidl_cargo/sensor_msgs". Cargo
# discovers config from the CWD upward, so at the workspace root no patches are
# in scope: cargo re-resolves the wildcard ROS message crates against crates.io
# and dies on the yanked sensor_msgs 4.2.3. That makes `cargo nextest run` at the
# root impossible and leaves the L-16 bindgen.lock guard reading a file that does
# not exist.
#
# This script copies one generated per-package block to the root with the
# relative paths rewritten root-relative (../../build/... -> build/...). The
# [build] rustflags are absolute already and carry over unchanged.
#
# It is run by `just build` (after colcon, so the per-package configs are fresh)
# and by `just test`. The output is ALWAYS regenerated, never hand-maintained:
# CLAUDE.md Known Issue 1 documents that a *stale* root config makes builds fail
# with "Unable to update .../install/.../rust". /.cargo/ stays gitignored.

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$repo_root"

out=.cargo/config.toml

# Pick a source deterministically so the generated file is stable across runs
# (an unstable file would churn cargo fingerprints on every build).
mapfile -t sources < <(find ros -mindepth 3 -maxdepth 3 \
    -path 'ros/*/.cargo/config.toml' -type f | sort)

if [[ ${#sources[@]} -eq 0 ]]; then
    cat >&2 <<'EOF'
error: no per-package .cargo/config.toml found under ros/*/.cargo/

  These are generated by colcon-cargo-ros2 and carry the [patch.crates-io]
  block that redirects the wildcard ROS message crates at build/ instead of
  crates.io. Without one there is nothing to synthesise a root config from,
  and cargo at the repo root will fail on the yanked sensor_msgs 4.2.3.

  Fix with:  just build
EOF
    exit 1
fi

src=${sources[0]}

# Every patch path in a per-package config must be "../../<something>", i.e.
# relative to ros/<pkg>/. If colcon-cargo-ros2 ever changes that layout the
# naive rewrite below would produce a silently wrong root config, so refuse
# rather than guess.
if bad=$(grep -oP 'path = "\K[^"]+' "$src" | grep -v '^\.\./\.\./' || true); [[ -n "$bad" ]]; then
    echo "error: unexpected patch path shape in $src:" >&2
    printf '       %s\n' $bad >&2
    echo "       expected every path to start with ../../ (relative to ros/<pkg>/)." >&2
    echo "       colcon-cargo-ros2's output layout changed; update $0." >&2
    exit 1
fi

mkdir -p .cargo
tmp=$(mktemp "${out}.XXXXXX")
trap 'rm -f "$tmp"' EXIT

{
    echo "# GENERATED by setup/scripts/sync-root-cargo-config.sh - DO NOT EDIT."
    echo "# Synthesised from $src with patch paths rewritten root-relative (M-18)."
    echo "# Regenerated by every \`just build\` / \`just test\`; a stale copy breaks"
    echo "# the build (CLAUDE.md Known Issue 1). Delete it freely - it is gitignored."
    echo
    # ../../foo (relative to ros/<pkg>/) is foo at the root.
    sed 's|path = "\.\./\.\./|path = "|g' "$src"
} >"$tmp"

chmod 644 "$tmp"   # mktemp gives 0600; this file is plain generated config
mv "$tmp" "$out"
trap - EXIT

echo "root .cargo/config.toml synthesised from $src"
