[package]
name = "calibration-target"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
json5 = { workspace = true }
sha2 = { workspace = true }
nalgebra = { workspace = true }
indexmap = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
