---
- name: Install development and testing tools
  become: true
  ansible.builtin.apt:
    name:
      - gdb
      - valgrind
      - strace
      - ltrace
      - perf-tools-unstable
      - linux-tools-generic
      - libgtest-dev
      - lcov
      - pybind11-dev
      - python3-pybind11
    state: present

- name: Install code quality tools
  become: true
  ansible.builtin.apt:
    name:
      - cppcheck
      - iwyu
      - ccache
    state: present

- name: Install documentation tools
  become: true
  ansible.builtin.apt:
    name:
      - doxygen
      - graphviz
    state: present