<?xml version="1.0"?>
<package format="3">
  <name>iou_overlapping</name>
  <version>0.1.0</version>
  <description>Extrinsic matrix evaluator: IoU between board ground-truth mask and LiDAR-projected points.</description>

  <maintainer email="dev@lctk.local">LCTK</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>




