use anyhow::Result;
use sensor_msgs::msg::CameraInfo;
use serde::{de::Error as _, Deserialize, Deserializer};

/// The type defines the calibration parameter file generated by MRPT
/// camera-calib.
#[derive(Debug, Clone, Deserialize)]
pub struct MrptCalibration {
    pub camera_name: String,
    pub focal_length_meters: f64,
    pub image_height: usize,
    pub image_width: usize,
    pub distortion_model: DistortionModel,
    pub distortion_coefficients: Matrix,
    pub camera_matrix: Matrix,
    pub projection_matrix: Matrix,
    pub rectification_matrix: Matrix,
}

impl MrptCalibration {
    pub fn to_camera_info(&self) -> Result<CameraInfo> {
        use anyhow::ensure;
        use slice_of_array::prelude::*;

        // Validate matrix dimensions
        ensure!(
            self.camera_matrix.rows == 3 && self.camera_matrix.cols == 3,
            "Camera matrix must be 3x3, got {}x{}",
            self.camera_matrix.rows,
            self.camera_matrix.cols
        );
        ensure!(
            self.distortion_coefficients.rows == 1 && self.distortion_coefficients.cols >= 5,
            "Distortion coefficients must be at least 1x5, got {}x{}",
            self.distortion_coefficients.rows,
            self.distortion_coefficients.cols
        );

        // Check that extra distortion coefficients (if any) are zero
        if self.distortion_coefficients.cols > 5 {
            let is_all_zero = self.distortion_coefficients.data[5..]
                .iter()
                .all(|&val| val == 0.0);
            ensure!(
                is_all_zero,
                "Distortion coefficients beyond index 5 must be zero for plumb_bob model"
            );
        }

        let mut camera_info = CameraInfo::default();

        // Set image dimensions
        camera_info.width = self.image_width as u32;
        camera_info.height = self.image_height as u32;

        // Set distortion model
        camera_info.distortion_model = match self.distortion_model {
            DistortionModel::PlumbBob => "plumb_bob".to_string(),
        };

        // Convert camera matrix to K array (row-major 3x3)
        // The data is stored row-major in the Matrix struct
        let cm_data: &[[f64; 3]] = self.camera_matrix.data.nest();
        camera_info.k = [
            cm_data[0][0],
            cm_data[0][1],
            cm_data[0][2],
            cm_data[1][0],
            cm_data[1][1],
            cm_data[1][2],
            cm_data[2][0],
            cm_data[2][1],
            cm_data[2][2],
        ];

        // Convert distortion coefficients
        camera_info.d = self.distortion_coefficients.data[0..5]
            .iter()
            .map(|&r| r)
            .collect();

        // Set projection matrix P (3x4)
        if self.projection_matrix.rows == 3 && self.projection_matrix.cols == 4 {
            let p_data = &self.projection_matrix.data;
            camera_info.p = [
                p_data[0], p_data[1], p_data[2], p_data[3], p_data[4], p_data[5], p_data[6],
                p_data[7], p_data[8], p_data[9], p_data[10], p_data[11],
            ];
        } else {
            // If projection matrix is not 3x4, use camera matrix with zero translation
            camera_info.p = [
                cm_data[0][0],
                cm_data[0][1],
                cm_data[0][2],
                0.0,
                cm_data[1][0],
                cm_data[1][1],
                cm_data[1][2],
                0.0,
                cm_data[2][0],
                cm_data[2][1],
                cm_data[2][2],
                0.0,
            ];
        }

        // Set rectification matrix R (3x3)
        if self.rectification_matrix.rows == 3 && self.rectification_matrix.cols == 3 {
            let r_data: &[[f64; 3]] = self.rectification_matrix.data.nest();
            camera_info.r = [
                r_data[0][0],
                r_data[0][1],
                r_data[0][2],
                r_data[1][0],
                r_data[1][1],
                r_data[1][2],
                r_data[2][0],
                r_data[2][1],
                r_data[2][2],
            ];
        } else {
            // Default to identity matrix if rectification matrix is not 3x3
            camera_info.r = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0];
        }

        // ROI and binning are not provided by MRPT calibration, use defaults
        camera_info.binning_x = 0;
        camera_info.binning_y = 0;
        // roi will be default (all zeros)

        Ok(camera_info)
    }
}

#[derive(Debug, Clone)]
pub struct Matrix {
    rows: usize,
    cols: usize,
    data: Vec<f64>,
}

impl<'de> Deserialize<'de> for Matrix {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let UncheckedMatrix { rows, cols, data } = UncheckedMatrix::deserialize(deserializer)?;
        if rows * cols != data.len() {
            return Err(D::Error::custom(format!(
                "data size ({}) does not match rows ({}) and cols ({})",
                data.len(),
                rows,
                cols
            )));
        }
        Ok(Self { rows, cols, data })
    }
}

#[derive(Debug, Clone, Deserialize)]
pub struct UncheckedMatrix {
    rows: usize,
    cols: usize,
    data: Vec<f64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DistortionModel {
    PlumbBob,
}
