[package]
name = "dynamic-calibration"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
calibration-quality = { version = "0.1.0", path = "../calibration-quality" }
nalgebra = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }