---
- name: Install OpenCV and related libraries
  become: true
  ansible.builtin.apt:
    name:
      - libopencv-dev
      - opencv-data
      - python3-opencv
    state: present

- name: Set OpenCV environment variable
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export OPENCV_PKGCONFIG_NAME=opencv4'
    create: true
    state: present