[package]
name = "calibration_board_locator"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
aruco-config = { version = "0.1.0", path = "../../lib/aruco-config" }
geometry_msgs = "4.8.0"
hollow-board-config = { version = "0.1.0", path = "../../lib/hollow-board-config", features = ["kiss3d"] }
hollow-board-detector = { version = "0.1.0", path = "../../lib/hollow-board-detector" }
json5 = { workspace = true }
once_cell = { workspace = true }
pcd-rs = { workspace = true }
rclrs = "0.4.0"
sensor_msgs = "4.8.0"
serde = { workspace = true }
serde_json = { workspace = true }
std_msgs = "4.8.0"
vision_msgs = "4.1.1"

[dependencies.nalgebra]
workspace = true
