---
- name: Install colcon extensions for Rust
  ansible.builtin.pip:
    name:
      - git+https://github.com/jerry73204/colcon-cargo.git
      - git+https://github.com/colcon/colcon-ros-cargo.git
    extra_args: --user --force-reinstall
    executable: /usr/bin/pip3
    state: present
