[package]
name = "hollow-board-detector"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { workspace = true, features = ["serde"] }
sample-consensus = "1.0.2"
approx = { workspace = true }
itertools = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
noisy_float = { workspace = true }
arrsac = "0.10.0"
rand = { workspace = true }
unzip-n = { workspace = true }
hollow-board-config = { version = "0.1.0", path = "../hollow-board-config" }
aruco-config = { version = "0.1.0", path = "../aruco-config" }
plane-estimator = { version = "0.1.0", path = "../plane-estimator" }

[dependencies.newslab-geom-algo]
git = "https://github.com/NEWSLabNTU/newslab-geom-algo.git"
tag = "v0.2.1"

[dev-dependencies]
clap = { workspace = true }
json5 = { workspace = true }
pcd-rs = { workspace = true }
